parameters:
#    bluga_admin.example.class: Bluga\AdminBundle\Example

services:
#    bluga_admin.example:
#        class: %bluga_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
